name: Update Chess Calendar

on:
  schedule:
    # Run daily at 6 AM UTC (1 AM CST / 2 AM CDT)
    - cron: "0 6 * * *"
  
  # Allow manual triggering
  workflow_dispatch:
  
  # Run on pushes to main branch for testing
  push:
    branches: [ main ]

jobs:
  update-calendar:
    runs-on: ubuntu-latest
    
    permissions:
      contents: write  # Required to push changes back to repo
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
          
      - name: Cache pip dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
            
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      - name: Generate calendar
        run: |
          python generate_calendar.py
          
      - name: Check if calendar was generated
        run: |
          if [ ! -f calendar.ics ]; then
            echo "❌ Calendar file was not generated"
            exit 1
          fi
          echo "✅ Calendar file generated successfully"
          ls -la calendar.ics
          
      - name: Commit and push changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          
          # Add the calendar file
          git add calendar.ics
          
          # Check if there are changes to commit
          if git diff --staged --quiet; then
            echo "No changes to commit"
          else
            git commit -m "🗓️ Auto-update chess tournament calendar - $(date -u '+%Y-%m-%d %H:%M:%S UTC')"
            git push
            echo "✅ Calendar updated and pushed to repository"
          fi
          
      - name: Display calendar info
        run: |
          echo "📊 Calendar Statistics:"
          echo "File size: $(du -h calendar.ics | cut -f1)"
          echo "Number of events: $(grep -c 'BEGIN:VEVENT' calendar.ics || echo '0')"
          echo ""
          echo "🔗 Calendar Feed URL:"
          echo "https://${{ github.repository_owner }}.github.io/${{ github.event.repository.name }}/calendar.ics"
